services:
  - type: web
    name: notreally-backend
    env: python
    rootDir: backend
    plan: free
    autoDeploy: true
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 1 --threads 4 --timeout 600
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.14
      - key: NOTREALLY_DB_PATH
        value: /tmp/notreally.db
      - key: NOTREALLY_UPLOAD_DIR
        value: /tmp/uploads

